#
# ~/.config/tmux/tmux.conf
#

set -s escape-time 0
set -g history-limit 50000
set -g display-time 4000
set -g status-interval 5
set -g default-terminal "screen-256color"
set -g status-keys vi
set -g aggressive-resize on

# Plugins
set -g @plugin 'tmux-plugins/tmux-battery'
set -g status-right 'Bat: #{battery_percentage} | %d. %m. %Y %H:%M '
run '~/.config/tmux/plugins/tpm/tpm'
