source $HOME/.config/dotfiles/common/zsh/zprofile

export EDITOR='code --wait'
export GOPRIVATE=github.com/devrev
export COLIMA_HOME=$XDG_CONFIG_HOME/colima

export ARCUS_API_KEY=$(security find-generic-password -a devrev -s arcus-token -w)
export DEVREV_API_KEY=$(security find-generic-password -a devrev -s devrev-token -w)
