# Advanced subtitles search
sub-auto=fuzzy

save-position-on-quit
volume-max=150

# Screenshot config
screenshot-format=png
screenshot-png-compression=8
screenshot-template='~/Pictures/Screenshots/%F (%P) %n'

# Force max bitrate for HLS
hls-bitrate=max
