#!/bin/sh
# Script for setting up mirror urls for this repo, since I clone it so much
git remote set-url --add --push origin git@github.com:erazemk/dotfiles.git
git remote set-url --add --push origin git@gitlab.com:erazemk/dotfiles.git

# Check if everything was set up correctly
git remote -v
